name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build Apps
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win -p never
      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: win-app
          path: dist/*.exe

      - name: Build Mac
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac -p never
      - name: Upload Mac Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/*.dmg
      - name: Build Mac Intel
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac --x64 -p never
      - name: Upload Mac Intel Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: mac-intel-app
          path: dist/*x64.dmg

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: npx electron-builder --linux -p never
      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: dist/*.AppImage

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: win-app
          path: dist/
      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-app
          path: dist/
      - name: Download Mac Intel Artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-intel-app
          path: dist/
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-app
          path: dist/
          
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
