name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger this workflow when a version tag (e.g. v1.0.1) is pushed

# Add this permissions block:
permissions:
  contents: write

jobs:
  release:
    name: Build and Release App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish Release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mac_certs: false
          mac_certs_password: false
          release: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
